
-- Remove the FK constraint from profiles.id to auth.users(id)
-- The app uses anonymous profiles (no Supabase Auth login).
-- The profile ID is a standalone UUID generated by gen_random_uuid().
-- This fixes the "Failed to create profile" error when auth.admin.createUser
-- is unavailable or fails.

ALTER TABLE profiles DROP CONSTRAINT IF EXISTS profiles_id_fkey;

-- Change the primary key column to have a default UUID
-- so inserts without an explicit ID still work
ALTER TABLE profiles ALTER COLUMN id SET DEFAULT gen_random_uuid();
